# -*- coding: utf-8 -*-
"""Abalone_KNN_js

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sy65caN9o5u7ZdL9kqx6mSPBSpRNTEAg
"""

# Step 1 - Import all required binaries
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix

# Step 2 - Read data into a data frame
names = ['Sex', 'Length', 'Diameter', 'Height', 'Whole weight', 'Shucked weight', 'Viscera weight', 'Shell weight', 'Rings']
df = pd.read_csv('/content/abalone.data', names=names, sep=',')

df.head()

# Step 3 - Preprocess the data
df.dtypes

df.isna().sum()

df.columns

df.drop('Sex', axis=1, inplace=True)

df.columns

# Step 4 - Define X and y
X = df[['Length', 'Diameter', 'Height', 'Whole weight', 'Shucked weight',
       'Viscera weight', 'Shell weight']]
y = df['Rings']

# Step 5 - Split X and y into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=45)

knn = KNeighborsClassifier(n_neighbors=3)

knn.fit(X_train, y_train)

knn.score(X_train, y_train)

